name :  First Workflow
on :  push
jobs  : 
  first-job  : 
    runs-on :  ubuntu-latest
    steps  : 
      - name :  Print greeting
        run :  echo "Hello World!"
      - name  :  Print goodbye
        run  :  echo "Done - bye!"
      - name: task-3
        run: echo "It's a new task"
